---
version: "2"
services:
  homedah:
    build: .
    container_name: ran-home-dashboard
    volumes:
      - /your/local/assets/:/www/assets
    ports:
      - 8080:8080
    environment:
      - UID=1000
      - GID=1000
    restart: unless-stopped
