---
version: "2"
services:
  homedah:
    build: .
    container_name: ran-home-dashboard
    volumes:
      - test:/www/assets
    ports:
      - 9780:8080
    environment:
      - UID=1000
      - GID=1000
    restart: unless-stopped

volumes:
  test:
